module.exports = [
  {
    files: ['**/*.js'],
    ignores: ['node_modules/**', 'dist/**', 'vite.config.js', '*.test.js', 'sw.js', 'layer-tests.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      // App scripts are ES modules (upgrade plan A3): explicit imports replace the
      // old window.* glue. no-undef now verifies every cross-file reference is
      // imported — project names are deliberately NOT declared as globals below.
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        Image: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        fetch: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Intl: 'readonly',
        Array: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        RegExp: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Symbol: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        RangeError: 'readonly',
        Uint8Array: 'readonly',
        Uint16Array: 'readonly',
        Uint32Array: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        ArrayBuffer: 'readonly',
        SharedArrayBuffer: 'readonly',
        DataView: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLLinkElement: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        performance: 'readonly',
        requestIdleCallback: 'readonly',
        cancelAnimationFrame: 'readonly',
        crypto: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        // Project globals (declared in code, not true globals)
        // S, pages, isAnimating, cursiveConnector, getDiagramImage, PAGE_W, PAGE_H
        // are declared in index.js and used by other modules via window.*
        PDFDocument: 'readonly',
        jsPDF: 'readonly',
        mermaid: 'readonly',
        Rough: 'readonly',
        ot: 'readonly',
        mammoth: 'readonly',
        tf: 'readonly',
        FontFace: 'readonly',
        OffscreenCanvas: 'readonly',
        MediaRecorder: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        SpeechRecognition: 'readonly',
        webkitSpeechRecognition: 'readonly',
        ClipboardItem: 'readonly',
        showDirectoryPicker: 'readonly',
        FileSystemHandle: 'readonly',
        // Module globals
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        WebSocket: 'readonly',
        Path2D: 'readonly',
        DOMParser: 'readonly',
        rough: 'readonly',
        screen: 'readonly',
        // NOTE: cross-module project names (S, pages, PAGE_W/PAGE_H, cursiveConnector,
        // getDiagramImage, showExportToast, CursiveConnector, MarkdownParser, …) are
        // intentionally NOT global — they are ES-module imports since the A3 conversion.
      },
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          // Phase B4: all 113 inline handlers are addEventListener-bound
          // (ui-bindings.js / layer-panel.js), so the former 40-name
          // varsIgnorePattern allowlist is gone — every binding target is
          // either imported, exported, or deleted.
          argsIgnorePattern: '^_',
        },
      ],
      'no-undef': 'error',
      'no-redeclare': 'warn',
      'no-constant-condition': 'warn',
      'no-empty': 'warn',
      'eqeqeq': ['warn', 'always'],
      'no-var': 'warn',
      'prefer-const': ['warn', { destructuring: 'all' }],
    },
  },
];
