import { defineConfig } from 'vite'
import { cpSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

// B5 (docs/upgrade-plan.md): Rollup bundles the whole app into content-hashed
// filenames (assets/index-<hash>.js, assets/index-<hash>.css, …) and the service
// worker's precache list is REGENERATED from the actual dist/ output on every
// build, so it can never drift from what was emitted (this exact drift class
// broke the SW twice — the 1.8.0 dist/index.css bug). Vite rewrites index.html's
// hashed references automatically.
//
// Still copied verbatim: sw.js must remain a classic script at the site root; the
// standalone About page and brand assets keep their exact precached URLs.
const COPY_ROOT_STATIC = ['sw.js', 'manifest.json', 'about.html', 'about.css', 'inkflow_logo.jpeg']

// Markers in sw.js around the precache section this build regenerates. Keep the
// two strings byte-identical to the comments in sw.js (including indentation).
const PRECACHE_BEGIN = '  // >>> BUILD-PRECACHE:BEGIN (regenerated by `vite build` — do not edit) >>>'
const PRECACHE_END = '  // <<< BUILD-PRECACHE:END <<<'

function walkDist(dir) {
  const files = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) files.push(...walkDist(full))
    else files.push(full)
  }
  return files
}

// Every emitted dist file as a site-root URL path, '/' for dist/index.html.
// sw.js itself is excluded (it is the file being edited) and docs/ is
// deployment material, not part of the app shell.
function collectPrecacheUrls() {
  const urls = new Set(['/'])
  for (const file of walkDist('dist')) {
    const rel = relative('dist', file).split(sep).join('/')
    if (rel === 'sw.js' || rel === 'index.html' || rel.startsWith('docs/')) continue
    urls.add(`/${rel}`)
  }
  return [...urls].sort() // '/' sorts first
}

// Rewrite the marked PRECACHE_URLS section inside dist/sw.js (the copy — the
// root sw.js keeps its placeholder content as a valid dev/fallback list).
function injectPrecacheList() {
  const swPath = join('dist', 'sw.js')
  let sw = readFileSync(swPath, 'utf8')
  const begin = sw.indexOf(PRECACHE_BEGIN)
  const end = sw.indexOf(PRECACHE_END)
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error('vite.config.js: BUILD-PRECACHE markers missing or out of order in sw.js')
  }
  const body = collectPrecacheUrls()
    .map((url) => `  ${JSON.stringify(url)},`)
    .join('\n')
  sw = `${sw.slice(0, begin + PRECACHE_BEGIN.length)}\n${body}\n${sw.slice(end)}`
  writeFileSync(swPath, sw)
}

export default defineConfig({
  root: '.',
  publicDir: false,
  plugins: [
    {
      name: 'copy-root-static',
      closeBundle() {
        for (const file of COPY_ROOT_STATIC) {
          cpSync(file, `dist/${file}`)
        }
        // B5: the precache list is derived from the real output, after the copies.
        injectPrecacheList()
      }
    }
  ],
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: 'index.html',
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
      }
    }
  },
  server: {
    open: process.env.CI ? false : true
  }
})
